grpc_server_port: !ENV ${GRPC_SERVER_PORT=50053}
rest_server_port: !ENV ${REST_SERVER_PORT=50053}
log:
  level: !ENV ${LOG_LEVEL=info}
  max_size: !ENV ${LOG_MAX_SIZE=100} # MB
  max_backups: !ENV ${LOG_MAX_BACKUPS=5}
  max_age: !ENV ${LOG_MAX_AGE=30} # days
  compress: !ENV ${LOG_COMPRESS=false}

