# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/speech_to_text.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/speech_to_text.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/speech_to_text.proto\x12\x0espeech_to_text\"=\n\x13SpeechToTextRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x15\n\rlanguage_code\x18\x02 \x01(\t\"<\n\x14SpeechToTextResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\t\"C\n\x19SpeechToTextStreamRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x15\n\rlanguage_code\x18\x02 \x01(\t\"R\n\x1aSpeechToTextStreamResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x10\n\x08start_ms\x18\x02 \x01(\t\x12\x0e\n\x06\x65nd_ms\x18\x03 \x01(\t2\xe1\x01\n\x13SpeechToTextService\x12Y\n\x0cSpeechToText\x12#.speech_to_text.SpeechToTextRequest\x1a$.speech_to_text.SpeechToTextResponse\x12o\n\x12SpeechToTextStream\x12).speech_to_text.SpeechToTextStreamRequest\x1a*.speech_to_text.SpeechToTextStreamResponse(\x01\x30\x01\x42\x43ZAgitlab.com/icom/translate/gen/proto/speech_to_text;speech_to_textb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.speech_to_text_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgitlab.com/icom/translate/gen/proto/speech_to_text;speech_to_text'
  _globals['_SPEECHTOTEXTREQUEST']._serialized_start=46
  _globals['_SPEECHTOTEXTREQUEST']._serialized_end=107
  _globals['_SPEECHTOTEXTRESPONSE']._serialized_start=109
  _globals['_SPEECHTOTEXTRESPONSE']._serialized_end=169
  _globals['_SPEECHTOTEXTSTREAMREQUEST']._serialized_start=171
  _globals['_SPEECHTOTEXTSTREAMREQUEST']._serialized_end=238
  _globals['_SPEECHTOTEXTSTREAMRESPONSE']._serialized_start=240
  _globals['_SPEECHTOTEXTSTREAMRESPONSE']._serialized_end=322
  _globals['_SPEECHTOTEXTSERVICE']._serialized_start=325
  _globals['_SPEECHTOTEXTSERVICE']._serialized_end=550
# @@protoc_insertion_point(module_scope)
