# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import speech_to_text_pb2 as proto_dot_speech__to__text__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/speech_to_text_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeechToTextServiceStub(object):
    """The SpeechToTextService definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpeechToText = channel.unary_unary(
                '/speech_to_text.SpeechToTextService/SpeechToText',
                request_serializer=proto_dot_speech__to__text__pb2.SpeechToTextRequest.SerializeToString,
                response_deserializer=proto_dot_speech__to__text__pb2.SpeechToTextResponse.FromString,
                _registered_method=True)
        self.SpeechToTextStream = channel.stream_stream(
                '/speech_to_text.SpeechToTextService/SpeechToTextStream',
                request_serializer=proto_dot_speech__to__text__pb2.SpeechToTextStreamRequest.SerializeToString,
                response_deserializer=proto_dot_speech__to__text__pb2.SpeechToTextStreamResponse.FromString,
                _registered_method=True)


class SpeechToTextServiceServicer(object):
    """The SpeechToTextService definition.
    """

    def SpeechToText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpeechToTextStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechToTextServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpeechToText': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeechToText,
                    request_deserializer=proto_dot_speech__to__text__pb2.SpeechToTextRequest.FromString,
                    response_serializer=proto_dot_speech__to__text__pb2.SpeechToTextResponse.SerializeToString,
            ),
            'SpeechToTextStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SpeechToTextStream,
                    request_deserializer=proto_dot_speech__to__text__pb2.SpeechToTextStreamRequest.FromString,
                    response_serializer=proto_dot_speech__to__text__pb2.SpeechToTextStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speech_to_text.SpeechToTextService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('speech_to_text.SpeechToTextService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeechToTextService(object):
    """The SpeechToTextService definition.
    """

    @staticmethod
    def SpeechToText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speech_to_text.SpeechToTextService/SpeechToText',
            proto_dot_speech__to__text__pb2.SpeechToTextRequest.SerializeToString,
            proto_dot_speech__to__text__pb2.SpeechToTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpeechToTextStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/speech_to_text.SpeechToTextService/SpeechToTextStream',
            proto_dot_speech__to__text__pb2.SpeechToTextStreamRequest.SerializeToString,
            proto_dot_speech__to__text__pb2.SpeechToTextStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
